<?xml version="1.0"?>
<package format="2">
  <name>saft_city_description</name>
  <version>0.1.0</version>
  <description>Robot description models for Safe City (平安城市) RAICOM 2026 competition robot</description>
  <maintainer email="xuan@todo.todo">xuan</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>joint_state_publisher</depend>
  <depend>robot_state_publisher</depend>
  <depend>roslaunch</depend>
  <depend>urdf</depend>
  <depend>xacro</depend>

  <depend>rviz</depend>
  <depend>gazebo_ros</depend>
  <depend>gazebo_plugins</depend>

  <export>
    <gazebo_ros gazebo_model_path="${prefix}/../"/>
  </export>
</package>
