global_frame:           odom
robot_base_frame:       base_link
update_frequency:       2.0
publish_frequency:      1.0
transform_tolerance:    0.5
resolution:             0.03
rolling_window:         true
width:                  100.0
height:                 100.0
plugins:
  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,       type: "costmap_2d::InflationLayer"}
