max_vel_x:              3.0
min_vel_x:              -0.2
max_vel_y:              0.0
min_vel_y:              0.0
max_vel_trans:          3.0
min_vel_trans:          0.15
max_vel_theta:          4.0
min_vel_theta:          -4.0
acc_lim_x:              6.0
acc_lim_y:              0.0
acc_lim_theta:          6.0

xy_goal_tolerance:      0.10
yaw_goal_tolerance:     0.30
latch_xy_goal_tolerance: true

sim_time:               2.0
sim_granularity:        0.025
vx_samples:             8
vy_samples:             1
vtheta_samples:         24
controller_frequency:   8.0

path_distance_bias:     40.0
goal_distance_bias:     20.0
occdist_scale:          0.2
forward_point_distance: 0.5
stop_time_buffer:       0.2
scaling_speed:          0.25
max_scaling_factor:     0.2

oscillation_reset_dist: 0.1
publish_traj_pc:        true
publish_cost_grid_pc:   true
